version: '3'

services:

  postgresql:
    image: postgres:13.5-bullseye
    container_name: postgredb
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/data
      - ./db/rates.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/rates?date_from=2021-01-01&date_to=2021-01-31&orig_code=CNGGZ&dest_code=EETLL"]
        interval: 30s
        timeout: 10s
        retries: 5

  web:
    container_name: apiservice
    image: apiservice:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - postgresql
    links: 
        - postgresql
    volumes:
      - ./rates:/home/app/rates
